management:
  server:
    port: 8183

spring:
  main:
    allow-bean-definition-overriding: "true"
  server:
    protocol: http
    url: localhost:8083
  data:
    jpa.repositories.enabled: true
    jpa:
      properties:
        hibernate:
          temp.use_jdbc_metadata_defaults: false
          ddl-auto: none
          use-new-id-generator-mappings: false
          default_schema: @project.artifactId@
      show-sql: true
      format_sql: true
    flyway:
      enabled: true
      locations: classpath:/db/migration,classpath:/db/local
      schemas: @project.artifactId@
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    driverClassName: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
    initialization-mode: always
  kafka:
    bootstrap-servers: adelpozo.servicebus.windows.net:9093,localhost:9092
    client-id: first-producer
    properties:
      request.timeout.ms: 60000
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://adelpozo.servicebus.windows.net/;SharedAccessKeyName=SendAndProduceAccessKey;SharedAccessKey=daXRnk3wt90wYKqNiFiKS5UkPOWXYMGJqbWSmcbS5yM=";
      sasl.mechanism: PLAIN
      security.protocol: SASL_SSL
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    consumer:
      group-id: $Default
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  h2:
    console:
      enabled: true

stratio:
  kafka:
    starter:
      transactional:
        enabled: false
        transactionIdPrefix: @project.artifactId@
      consumer:
        enabled: true
        topics: eventhubtopic
        consumerGroupId: @project.artifactId@Group
      producer:
        enabled: true
        actionTopic:
          noaction: evenhubproducer