management:
  server:
    port: 8183

spring:
  main:
    allow-bean-definition-overriding: "true"
  server:
    protocol: http
    url: localhost:8083
  data:
    jpa.repositories.enabled: true
    jpa:
      properties:
        hibernate:
          temp.use_jdbc_metadata_defaults: false
          ddl-auto: none
          use-new-id-generator-mappings: false
          default_schema: @project.artifactId@
      show-sql: true
      format_sql: true
    flyway:
      enabled: true
      locations: classpath:/db/migration,classpath:/db/local
      schemas: @project.artifactId@
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    driverClassName: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
    initialization-mode: always
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  h2:
    console:
      enabled: true

stratio:
  kafka:
    starter:
      transactional:
        enabled: true
        transactionIdPrefix: @project.artifactId@
      consumer:
        enabled: true
        consumerGroupId: @project.artifactId@Group
        topics: kafkatopic
      producer:
        enabled: true
        actionTopic:
          noaction: kafkaproducer
        replicas: 1
        partitions: 1
      eventhub:
        enabled: true
        bootstrapServers: adelpozo.servicebus.windows.net:9093
        consumerGroupId: @project.artifactId@Group
        requestTimeoutMs: 60000
        securityProtocol: SASL_SSL
        saslMechanism: PLAIN
        saslJaasConfig: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://adelpozo.servicebus.windows.net/;SharedAccessKeyName=SendAndProduceAccessKey;SharedAccessKey=daXRnk3wt90wYKqNiFiKS5UkPOWXYMGJqbWSmcbS5yM=";
        topics: eventhubtopic
        actionTopic:
          noaction: evenhubproducer