spring:
  data:
    jpa.repositories.enabled: true
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:/db/migration
  datasource:
    driverClassName: org.postgresql.Driver
    continueOnError: true
  kafka:
    consumer:
      group-id: consumer-group-id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.JsonDeserializer
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
stratio:
  kafka:
    starter:
      transactional:
        enabled: true
        transactionIdPrefix: @project.artifactId@
      schemaRegistry:
        enabled: false
        url: http://localhost:8081
      consumer:
        enabled: true
        topics: normalTopic,priorityTopic
        consumerGroupId: @project.artifactId@Group
        concurrency: 2
        maxPollRecords: 30
      conductorWorker:
        enabled: true
        topicsPattern: "worker.*"
        consumerGroupId: @project.artifactId@Group
        concurrency: 2
        maxPollRecords: 30
      producer:
        enabled: true
        partitions: 1
        replicas: 1
        action-topic:
          someAction: topic-to-produce-to

