management:
  server:
    port: 8183

spring:
  main:
    allow-bean-definition-overriding: "true"
  server:
    protocol: http
    url: localhost:8083
  data:
    jpa.repositories.enabled: true
    jpa:
      properties:
        hibernate:
          temp.use_jdbc_metadata_defaults: false
          ddl-auto: none
          use-new-id-generator-mappings: false
          default_schema: @project.artifactId@
      show-sql: true
      format_sql: true
    flyway:
      enabled: true
      locations: classpath:/db/migration,classpath:/db/local
      schemas: @project.artifactId@
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: mysecretpassword
    initialization-mode: always
  kafka:
    bootstrap-servers: adelpozo.servicebus.windows.net:9093
    client-id: first-producer
    properties:
      request.timeout.ms: 60000
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://adelpozo.servicebus.windows.net/;SharedAccessKeyName=SendAndProduceAccessKey;SharedAccessKey=daXRnk3wt90wYKqNiFiKS5UkPOWXYMGJqbWSmcbS5yM=";
      sasl.mechanism: PLAIN
      security.protocol: SASL_SSL
    producer:
      value-serializer: com.stratio.financial.test.infrastructure.eventhub.ProducerMessageSerializer
    consumer:
      group-id: $Default
      properties:
        spring.json:
          use.type.headers: false
          value.default.type: com.stratio.financial.test.infrastructure.eventhub.SimpleMessage
  h2:
    console:
      enabled: true

#stratio:
#  kafka:
#    starter:
#      transactional:
#        enabled: false
#        transactionIdPrefix: @project.artifactId@
#      schemaRegistry:
#        enabled: false
#        url: http://localhost:8081
#      consumer:
#        enabled: true
#        topics: normalTopic,priorityTopic,test,sleep,throw,testFailure,throwdb
#        consumerGroupId: @project.artifactId@Group
#        concurrency: 2
#        maxPollRecords: 30
#      conductorWorker:
#        enabled: true
#        topicsPattern: "worker.*"
#        consumerGroupId: @project.artifactId@Group
#        concurrency: 2
#        maxPollRecords: 30
#      producer:
#        enabled: true
#        partitions: 1
#        replicas: 1
#        action-topic:
#          someAction: topic-to-produce-to
#          error: errorTest
#      rollBackConfig:
#        bussinessExceptions:
#          - com.stratio.financial.test.infrastructure.message.springkafka.ConsumerTestCustomException
#      cache:
#        enabled: false
